[tool.poetry]
name = "Clueless"
version = "2.1.1"
description = "A pxls.space stats discord bot and more!"
authors = ["GrayTurtles"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
aiohttp = "^3.8.1"
alive-progress = "^2.3.1"
bar-chart-race = "^0.1.0"
beautifulsoup4 = "^4.10.0"
disnake = "^2.4.0"
blend-modes = "^2.1.0"
matplotlib = "^3.5.1"
numpy = "^1.21"
opencv-python = "^4.5.5"
pandas = "^1.4.1"
Pillow = "^9.0.1"
plotly = "^5.6.0"
python-dotenv = "^0.19.2"
pytz = "^2021.3"
requests = "^2.27.1"
selenium = "^4.1.2"
websockets = "^10.2"
numba = "^0.55.1"
kaleido = "0.2.1"
rapptz-asqlite = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=90